/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/internal/vulnerabilities/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Consultar vulnerabilidades por CPE
         * @description Uso interno de Python, sin JWT ni CSRF. escaneoId es el UUID persistido en PostgreSQL, no jobId. Devuelve results indexado por CPE. Un fallo NVD se propaga como 502; un exceso de resultados como 429. Este DTO tiene @Valid pero no declara constraints; errores del servicio pueden resultar en 500.
         */
        post: operations["lookup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/scans/{jobId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recibir progreso desde Python
         * @description Uso interno, sin JWT ni CSRF en la configuración actual. jobId es el identificador del trabajo Python (moduloJobId), distinto del ID persistido del escaneo.
         */
        post: operations["receiveStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/internal/scans/{jobId}/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recibir resultado desde Python
         * @description Uso interno, sin JWT ni CSRF. jobId identifica el trabajo Python. El cuerpo contiene hosts y apiResults indexado por CPE.
         */
        post: operations["receiveCallback"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Registrar un usuario
         * @description Público. Requiere email, contrasenia y apiKey NVD según las validaciones actuales. La clave se almacena cifrada.
         */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Renovar el access token
         * @description Público. Requiere refreshToken en el cuerpo, incluso si existe una cookie refresh_token. Renueva access_token y XSRF-TOKEN.
         */
        post: operations["refresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión
         * @description Público. Devuelve tokens y establece cookies access_token, refresh_token y XSRF-TOKEN. Para escrituras con cookie access_token, enviar X-XSRF-TOKEN con el valor de XSRF-TOKEN.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar auditorías
         * @description Página de auditorías del usuario autenticado.
         */
        get: operations["findAll"];
        put?: never;
        /**
         * Crear una auditoría
         * @description Crea una auditoría para el usuario autenticado.
         */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/escaneos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar un escaneo
         * @description Crea el escaneo y solicita su ejecución asíncrona en Python. Consultar después status y logs. El 201 no implica que el reconocimiento haya finalizado.
         */
        post: operations["startScan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/usuarios/me/nvd-api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Actualizar la clave NVD del usuario
         * @description Actualiza la clave del usuario autenticado; no se devuelve la clave en la respuesta.
         */
        patch: operations["updateNvdApiKey"];
        trace?: never;
    };
    "/api/escaneos/{escaneoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Mover un escaneo a otra auditoría
         * @description auditoriaId en el cuerpo identifica la auditoría de destino.
         */
        patch: operations["mover"];
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar una auditoría
         * @description Detalle de una auditoría accesible para el usuario.
         */
        get: operations["findById"];
        put?: never;
        post?: never;
        /**
         * Eliminar una auditoría
         * @description Elimina la auditoría y sus datos asociados según el servicio actual.
         */
        delete: operations["deleteById"];
        options?: never;
        head?: never;
        /**
         * Actualizar una auditoría
         * @description Actualiza nombre y objetivo con las validaciones del DTO existente.
         */
        patch: operations["update"];
        trace?: never;
    };
    "/api/{auditoriaId}/escaneos/{escaneoId}/reporte": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Descargar un reporte
         * @description Requiere un escaneo COMPLETADO con resultado. MD descarga Markdown; CSV descarga un ZIP con archivos CSV. Se conserva la ruta /api/{auditoriaId}/escaneos/{escaneoId}/reporte.
         */
        get: operations["generarReporte"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vulnerabilities/{cveId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar detalle de un CVE
         * @description Busca el identificador público CVE en el catálogo persistido, sin distinguir mayúsculas. Actualmente un CVE inexistente termina en el manejador genérico 500.
         */
        get: operations["getByCveId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/escaneos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar escaneos del usuario
         * @description Devuelve BaseResponse con una Page de escaneos de las auditorías del usuario.
         */
        get: operations["findAll_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/estadisticas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar estadísticas de escaneos
         * @description Totales por estado de los escaneos de la auditoría.
         */
        get: operations["getEstadisticas"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/escaneos/{escaneoId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar estado y progreso
         * @description Consulta el estado persistido; scanId en esta respuesta es el ID del escaneo en PostgreSQL.
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/escaneos/{escaneoId}/resultado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar resultado de reconocimiento
         * @description Devuelve activos y puertos persistidos con el estado del escaneo.
         */
        get: operations["getResultado"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/escaneos/{escaneoId}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Leer salida incremental del módulo
         * @description Consulta logs por ID persistido del escaneo. available=false indica que el módulo o la salida no están disponibles; sigue siendo HTTP 200. Los logs son temporales y se pierden al reiniciar Python.
         */
        get: operations["logs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar dashboard de una auditoría
         * @description KPIs, historial, evolución del riesgo y desgloses de hosts/CVE del servicio actual.
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Consultar resumen de auditorías
         * @description Datos de las tarjetas del usuario autenticado.
         */
        get: operations["getResumen"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar activos agrupados
         * @description Página de activos deduplicados con sus IDs de escaneo.
         */
        get: operations["findAll_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activos/by-escaneo/{escaneoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar activos de un escaneo
         * @description Página de activos asociados al escaneo indicado.
         */
        get: operations["findByEscaneoId"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/auditorias/{auditoriaId}/escaneos/{escaneoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar un escaneo
         * @description El servicio resuelve la propiedad por escaneoId; auditoriaId forma parte de la ruta pero no se utiliza para resolver la eliminación.
         */
        delete: operations["deleteEscaneo"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/activos/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Eliminar un activo
         * @description Elimina el activo identificado.
         */
        delete: operations["deleteById_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description ProblemDetail del manejador de errores. errors, instance y timestamp pueden no estar presentes en errores de filtros o integración. */
        ApiProblem: {
            type?: string;
            title?: string;
            /** Format: int32 */
            status?: number;
            detail?: string;
            instance?: string;
            errors?: string[];
            /** Format: date-time */
            timestamp?: string;
        };
        NvdLookupRequest: {
            /**
             * Format: uuid
             * @description UUID persistido del escaneo. Permite resolver la clave NVD de su propietario; no enviar jobId.
             */
            escaneoId?: string;
            cpes?: string[];
            /**
             * Format: int32
             * @description Años de antigüedad máxima; 0 desactiva el filtro temporal.
             */
            maxCveYears?: number;
            /** @description Umbral CVSS inclusivo entre 0 y 10; null equivale a 0. */
            minCvssScore?: number;
        };
        NvdCacheEntry: {
            cpe?: string;
            /** Format: date-time */
            lastChecked?: string;
            vulnerabilities?: components["schemas"]["NvdVulnerabilityData"][];
        };
        NvdLookupResponse: {
            /** @description Resultados indexados por cadena CPE; pueden omitirse CPEs no consultables. */
            results?: {
                [key: string]: components["schemas"]["NvdCacheEntry"];
            };
        };
        NvdReferenceData: {
            url?: string;
            source?: string;
            tags?: string[];
        };
        NvdVulnerabilityData: {
            cveId?: string;
            description?: string;
            severity?: string;
            cvssScore?: number;
            cvssVector?: string;
            /** Format: date-time */
            publishedDate?: string;
            /** Format: date-time */
            lastModified?: string;
            cwes?: string[];
            references?: components["schemas"]["NvdReferenceData"][];
            exploitRefs?: string[];
            nistUrl?: string;
            mitigation?: string;
            vulnerableVersions?: string;
            fixType?: string;
            fixedVersion?: string;
        };
        ScanStatusResponse: {
            /**
             * Format: uuid
             * @description En GET status es el UUID persistido del escaneo; en el callback de progreso Python envía el UUID del trabajo.
             */
            scanId?: string;
            /** @enum {string} */
            status?: "PENDIENTE" | "EN_PROCESO" | "COMPLETADO" | "FALLO";
            /**
             * Format: int32
             * @description Porcentaje de progreso (0 a 100).
             */
            progress?: number;
            error?: string;
        };
        BaseResponseVoid: {
            data?: unknown;
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        EscaneoResult: {
            hosts?: components["schemas"]["HostResult"][];
            /** @description Mapa cuya clave es la cadena CPE; cada valor contiene las vulnerabilidades de ese CPE en el resultado Python. */
            apiResults?: {
                [key: string]: unknown;
            };
            nmapVersion?: string;
            startTime?: string;
            endTime?: string;
        };
        HostResult: {
            ip?: string;
            mac?: string;
            hostname?: string;
            os?: string;
            /** Format: int32 */
            soProbab?: number;
            puertos?: components["schemas"]["PuertoResultadoResponse"][];
        };
        PuertoResultadoResponse: {
            /** Format: int32 */
            numero?: number;
            protocolo?: string;
            /** @enum {string} */
            estado?: "OPEN" | "CLOSED" | "FILTERED" | "UNFILTERED" | "OPEN_OR_FILTERED" | "CLOSED_OR_FILTERED";
            servicio?: string;
            producto?: string;
            version?: string;
            extraInfo?: string;
            cpes?: string[];
        };
        RegisterRequestDto: {
            /** Format: email */
            email: string;
            contrasenia: string;
            apiKey: string;
        };
        RefreshRequestDto: {
            refreshToken: string;
        };
        BaseResponseRefreshResponseDto: {
            data?: components["schemas"]["RefreshResponseDto"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        RefreshResponseDto: {
            accessToken?: string;
            tokenType?: string;
            /**
             * Format: int64
             * @description Vigencia del access token en MILISEGUNDOS, conservando el nombre del contrato existente.
             */
            expiresIn?: number;
            csrfToken?: string;
        };
        LoginRequestDto: {
            /** Format: email */
            email: string;
            contrasenia: string;
        };
        AuthResponseDto: {
            /** Format: uuid */
            id?: string;
            accessToken?: string;
            refreshToken?: string;
            tokenType?: string;
            /** Format: int64 */
            expiresInMs?: number;
            email?: string;
            csrfToken?: string;
        };
        BaseResponseAuthResponseDto: {
            data?: components["schemas"]["AuthResponseDto"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        AuditoriaRequestDto: {
            nombre?: string;
            objetivo?: string;
        };
        AuditoriaResponse: {
            /** Format: uuid */
            id?: string;
            nombre?: string;
            objetivo?: string;
            /** Format: date-time */
            fechaGeneracion?: string;
            /** Format: date-time */
            fechaFinal?: string;
        };
        BaseResponseAuditoriaResponse: {
            data?: components["schemas"]["AuditoriaResponse"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        ScanStartRequest: {
            objetivos: string[];
            /**
             * Format: int32
             * @description Tiempo máximo en segundos de cada fase Nmap por objetivo; por defecto 600.
             */
            timeout?: number;
            /**
             * Format: int32
             * @description Espera ICMP en segundos; por defecto 5.
             */
            icmpTimeout?: number;
            /**
             * Format: int32
             * @description Antigüedad máxima de CVEs en años; por defecto 2. Cero desactiva el filtro temporal.
             */
            maxCveYears?: number;
            /**
             * Format: double
             * @description Umbral CVSS inclusivo de 0 a 10; por defecto 0.
             */
            minCvssScore?: number;
            /** @description Campo conservado por compatibilidad. El servicio actual obtiene la clave del usuario persistido y no utiliza este campo. */
            nvdApiKey?: string;
        };
        BaseResponseEscaneoResponse: {
            data?: components["schemas"]["EscaneoResponse"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        EscaneoResponse: {
            /** Format: uuid */
            escaneoId?: string;
            activos?: string[];
            /** @enum {string} */
            estado?: "PENDIENTE" | "EN_PROCESO" | "COMPLETADO" | "FALLO";
            /** Format: int32 */
            progreso?: number;
            nmapVersion?: string;
            mensajeError?: string;
            /** Format: date-time */
            iniciadoA?: string;
            /** Format: date-time */
            completadoA?: string;
            /** Format: date-time */
            creadoA?: string;
        };
        UpdateNvdApiKeyRequest: {
            apiKey: string;
        };
        MoverEscaneoRequest: {
            /** Format: uuid */
            auditoriaId: string;
        };
        BaseResponseCveDetalleResponse: {
            data?: components["schemas"]["CveDetalleResponse"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        CveDetalleResponse: {
            cveId?: string;
            descripcion?: string;
            severidad?: string;
            cvssScore?: number;
            cvssVector?: string;
            /** @description Probabilidad EPSS entre 0 y 1; null cuando no hay dato. */
            epssScore?: number;
            /** @description Indica pertenencia al catálogo CISA KEV. */
            explotacionActiva?: boolean;
            versionesVulnerables?: string;
            mitigacion?: string;
            versionParche?: string;
            tipoParche?: string;
            exploitRefs?: string[];
            nistUrl?: string;
            /** Format: date-time */
            fechaPublicacion?: string;
            /** Format: date-time */
            ultimaModificacion?: string;
        };
        BaseResponsePageEscaneoListadoResponse: {
            data?: components["schemas"]["PageEscaneoListadoResponse"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        EscaneoListadoResponse: {
            /** Format: uuid */
            escaneoId?: string;
            /** Format: uuid */
            auditoriaId?: string;
            auditoriaNombre?: string;
            objetivos?: string[];
            /** @enum {string} */
            estado?: "PENDIENTE" | "EN_PROCESO" | "COMPLETADO" | "FALLO";
            /** Format: int32 */
            progreso?: number;
            nmapVersion?: string;
            /** Format: date-time */
            iniciadoA?: string;
            /** Format: date-time */
            completadoA?: string;
        };
        PageEscaneoListadoResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["EscaneoListadoResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        PageableObject: {
            /** Format: int64 */
            offset?: number;
            paged?: boolean;
            /** Format: int32 */
            pageNumber?: number;
            /** Format: int32 */
            pageSize?: number;
            sort?: components["schemas"]["SortObject"];
            unpaged?: boolean;
        };
        SortObject: {
            empty?: boolean;
            sorted?: boolean;
            unsorted?: boolean;
        };
        PageAuditoriaResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["AuditoriaResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        AuditoriaEstadisticasResponse: {
            /** Format: int32 */
            totalEscaneos?: number;
            /** Format: int32 */
            escaneosCompletados?: number;
            /** Format: int32 */
            escaneosEnProceso?: number;
            /** Format: int32 */
            escaneosPendientes?: number;
            /** Format: int32 */
            escaneosFallidos?: number;
        };
        BaseResponseScanStatusResponse: {
            data?: components["schemas"]["ScanStatusResponse"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        ActivoResultadoResponse: {
            /** Format: uuid */
            activoId?: string;
            host?: string;
            hostname?: string;
            so?: string;
            /** Format: int32 */
            soProbab?: number;
            mac?: string;
            puertos?: components["schemas"]["PuertoResultadoResponse"][];
        };
        BaseResponseEscaneoResultResponse: {
            data?: components["schemas"]["EscaneoResultResponse"];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        EscaneoResultResponse: {
            /** Format: uuid */
            escaneoId?: string;
            /** @enum {string} */
            estado?: "PENDIENTE" | "EN_PROCESO" | "COMPLETADO" | "FALLO";
            /** Format: int32 */
            progreso?: number;
            nmapVersion?: string;
            /** Format: date-time */
            iniciadoA?: string;
            /** Format: date-time */
            completadoA?: string;
            activos?: components["schemas"]["ActivoResultadoResponse"][];
        };
        Line: {
            /** Format: int64 */
            seq?: number;
            timestamp?: string;
            text?: string;
        };
        Logs: {
            /** @description false si la salida expiró, el módulo reinició o no pudo consultarse */
            available?: boolean;
            lines?: components["schemas"]["Line"][];
            /**
             * Format: int64
             * @description Cursor que se debe enviar como after en la próxima consulta
             */
            nextCursor?: number;
            /** @description Se descartaron líneas anteriores al cursor por el límite del buffer */
            truncated?: boolean;
        };
        CveDesgloseResponse: {
            masComunes?: components["schemas"]["CveResumenResponse"][];
            explotacionActiva?: components["schemas"]["CveResumenResponse"][];
            mayorCriticidad?: components["schemas"]["CveResumenResponse"][];
            mayorProbabilidadExplotacion?: components["schemas"]["CveResumenResponse"][];
        };
        CveResumenResponse: {
            cveId?: string;
            /** Format: int64 */
            frecuencia?: number;
            cvssScore?: number;
            epssScore?: number;
            explotacionActiva?: boolean;
            cwes?: string[];
        };
        DashboardAuditoriaResponse: {
            kpis?: components["schemas"]["DashboardKpisResponse"];
            historial?: components["schemas"]["EjecucionHistorialResponse"][];
            riesgoTemporal?: components["schemas"]["RiesgoTemporalResponse"][];
            vulnerabilidades?: components["schemas"]["CveDesgloseResponse"];
            hosts?: components["schemas"]["HostDesgloseResponse"];
        };
        DashboardKpisResponse: {
            /** Format: int64 */
            escaneos?: number;
            /** Format: int64 */
            activos?: number;
            /** Format: int64 */
            puertos?: number;
            /** Format: int64 */
            cves?: number;
            /** Format: int64 */
            cvesCriticos?: number;
            /** Format: int64 */
            cvesAltos?: number;
            /** Format: int64 */
            cvesMedios?: number;
            /** Format: int64 */
            cvesBajos?: number;
            cvssPromedio?: number;
            /** Format: int64 */
            cvesExplotados?: number;
            epssPromedio?: number;
        };
        EjecucionHistorialResponse: {
            /** Format: uuid */
            escaneoId?: string;
            /** Format: date-time */
            fecha?: string;
            estado?: string;
            /** Format: int32 */
            progreso?: number;
            objetivos?: string[];
            /** Format: int64 */
            activos?: number;
            /** Format: int64 */
            puertos?: number;
            /** Format: int64 */
            cves?: number;
            /** Format: int64 */
            cvesCriticos?: number;
            cvssPromedio?: number;
            mensajeError?: string;
        };
        HostCveResponse: {
            cveId?: string;
            cvssScore?: number;
            epssScore?: number;
            kev?: boolean;
            cpes?: string[];
        };
        HostDesgloseResponse: {
            masVulnerabilidadesCriticas?: components["schemas"]["HostVulnerabilidadResponse"][];
            mayorRiesgoExplotacion?: components["schemas"]["HostVulnerabilidadResponse"][];
        };
        HostVulnerabilidadResponse: {
            ip?: string;
            hostname?: string;
            /** Format: int64 */
            vulnerabilidades?: number;
            /** Format: int64 */
            vulnerabilidadesCriticas?: number;
            cvssMaximo?: number;
            epssMaximo?: number;
            kev?: boolean;
            cvesCriticas?: components["schemas"]["HostCveResponse"][];
            cvesPrioritarias?: components["schemas"]["HostCveResponse"][];
        };
        RiesgoTemporalResponse: {
            /** Format: uuid */
            escaneoId?: string;
            /** Format: date-time */
            fecha?: string;
            nivel?: string;
            cvssPromedio?: number;
            /** Format: int64 */
            cves?: number;
            /** Format: int64 */
            cvesCriticos?: number;
            /** Format: int64 */
            cvesExplotados?: number;
        };
        AuditoriaResumenResponseDto: {
            /** Format: uuid */
            escaneoId?: string;
            /** Format: uuid */
            auditoriaId?: string;
            auditoriaNombre?: string;
            /** Format: int32 */
            activos?: number;
            /** Format: int32 */
            puertos?: number;
            /** Format: date-time */
            completadoA?: string;
            /** @enum {string} */
            status?: "PENDIENTE" | "EN_PROCESO" | "COMPLETADO" | "FALLO";
            /** Format: int32 */
            cve?: number;
            /** Format: int32 */
            cveCriticos?: number;
        };
        BaseResponseListAuditoriaResumenResponseDto: {
            data?: components["schemas"]["AuditoriaResumenResponseDto"][];
            message?: string;
            errors?: string[];
            timestamp?: string;
        };
        ActivoAgrupadoResponse: {
            host?: string;
            hostname?: string;
            so?: string;
            /** Format: int32 */
            soProbab?: number;
            mac?: string;
            descripcion?: string;
            escaneoIds?: string[];
        };
        PageActivoAgrupadoResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ActivoAgrupadoResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
        ActivoResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            escaneoId?: string;
            host?: string;
            hostname?: string;
            so?: string;
            /** Format: int32 */
            soProbab?: number;
            mac?: string;
            descripcion?: string;
        };
        PageActivoResponse: {
            /** Format: int32 */
            totalPages?: number;
            /** Format: int64 */
            totalElements?: number;
            /** Format: int32 */
            size?: number;
            content?: components["schemas"]["ActivoResponse"][];
            /** Format: int32 */
            number?: number;
            sort?: components["schemas"]["SortObject"];
            pageable?: components["schemas"]["PageableObject"];
            /** Format: int32 */
            numberOfElements?: number;
            first?: boolean;
            last?: boolean;
            empty?: boolean;
        };
    };
    responses: {
        /** @description Permisos insuficientes o CSRF inválido */
        Error403: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Error inesperado del servidor */
        Error500: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description JWT o credenciales ausentes, inválidos o expirados */
        Error401: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Validación o solicitud rechazada */
        Error400: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Conflicto con los datos existentes */
        Error409: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Límite de solicitudes o resultados excedido */
        Error429: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Fallo de consulta al proveedor NVD */
        Error502: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
        /** @description Recurso no encontrado o no accesible */
        Error404: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["ApiProblem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    lookup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NvdLookupRequest"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NvdLookupResponse"];
                };
            };
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
            502: components["responses"]["Error502"];
        };
    };
    receiveStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del trabajo Python (moduloJobId), no el UUID persistido del escaneo */
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanStatusResponse"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseVoid"];
                };
            };
            400: components["responses"]["Error400"];
            500: components["responses"]["Error500"];
        };
    };
    receiveCallback: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador del trabajo Python (moduloJobId), no el UUID persistido del escaneo */
                jobId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscaneoResult"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseVoid"];
                };
            };
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequestDto"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseVoid"];
                };
            };
            400: components["responses"]["Error400"];
            409: components["responses"]["Error409"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
        };
    };
    refresh: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequestDto"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseRefreshResponseDto"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequestDto"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseAuthResponseDto"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            429: components["responses"]["Error429"];
            500: components["responses"]["Error500"];
        };
    };
    findAll: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageAuditoriaResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            500: components["responses"]["Error500"];
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditoriaRequestDto"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseAuditoriaResponse"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            500: components["responses"]["Error500"];
        };
    };
    startScan: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanStartRequest"];
            };
        };
        responses: {
            /** @description Creado */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseEscaneoResponse"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    updateNvdApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNvdApiKeyRequest"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseVoid"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            409: components["responses"]["Error409"];
            500: components["responses"]["Error500"];
        };
    };
    mover: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoverEscaneoRequest"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseVoid"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    findById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriaResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    deleteById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado; sin cuerpo */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuditoriaRequestDto"];
            };
        };
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseAuditoriaResponse"];
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    generarReporte: {
        parameters: {
            query: {
                /** @description MD devuelve Markdown; CSV devuelve un ZIP de archivos CSV */
                formato: "MD" | "CSV";
            };
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Archivo descargable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/markdown": string;
                    "application/zip": string;
                };
            };
            400: components["responses"]["Error400"];
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    getByCveId: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identificador público CVE, por ejemplo CVE-2024-0001; no es un UUID */
                cveId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseCveDetalleResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            500: components["responses"]["Error500"];
        };
    };
    findAll_1: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponsePageEscaneoListadoResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            500: components["responses"]["Error500"];
        };
    };
    getEstadisticas: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditoriaEstadisticasResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseScanStatusResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    getResultado: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseEscaneoResultResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    logs: {
        parameters: {
            query?: {
                /** @description Último seq recibido; 0 inicia la lectura. Usar nextCursor de la respuesta siguiente */
                after?: number;
            };
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Logs"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID de la auditoría */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardAuditoriaResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    getResumen: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseResponseListAuditoriaResumenResponseDto"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            500: components["responses"]["Error500"];
        };
    };
    findAll_2: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageActivoAgrupadoResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            500: components["responses"]["Error500"];
        };
    };
    findByEscaneoId: {
        parameters: {
            query?: {
                /** @description Zero-based page index (0..N) */
                page?: number;
                /** @description The size of the page to be returned */
                size?: number;
                /** @description Sorting criteria in the format: property,(asc|desc). Default sort order is ascending. Multiple sort criteria are supported. */
                sort?: string[];
            };
            header?: never;
            path: {
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Operación completada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PageActivoResponse"];
                };
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    deleteEscaneo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID del escaneo persistido en PostgreSQL */
                escaneoId: string;
                /** @description UUID de la ruta; el servicio actual resuelve por escaneoId */
                auditoriaId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado; sin cuerpo */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
    deleteById_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Eliminado; sin cuerpo */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Error401"];
            403: components["responses"]["Error403"];
            404: components["responses"]["Error404"];
            500: components["responses"]["Error500"];
        };
    };
}
