spring.application.name=reconac

# ===============================
# SECURITY
# ===============================

spring.security.user.name=${SEC_NAME}
spring.security.user.password=${SEC_PASSWD}

# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWD}

# ===============================
# JPA / HIBERNATE
# ===============================

# Hibernate solo verifica que las entidades coincidan
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# FLYWAY
# ===============================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
logging.level.org.flywaydb=DEBUG

# ===============================
# REDIS
# ===============================

spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

# Cache TTL (hours)
cache.ttl-hours=${CACHE_TTL_HOURS:24}